tinygo-org/drivers

- bmp180/bmp180.go
- bmp180/registers.go
- examples/bmp180/main.go
Based on https://github.com/hybridgroup/gobot/blob/master/drivers/i2c/bmp180_driver.go
Added a examples/bmp180 folder with a tiny example
> Initial support for BMP180 digital pressure sensor

- examples/apa102/main.go
This PR adds an example for the APA102.
> examples: add example for apa102

- examples/vl53l1x/main.go
- vl53v1x/registers.go
- vl53v1x/vl53l1x.go
Basic support for VL53L1X time-of-flight distance sensor.
This driver was based on the library https://github.com/pololu/vl53l1x-arduino 
There's an official user manual and API implementation a little hard to read, and in some parts I blindly trust Pololu's implementation
>  Basic support for VL53L1X time-of-flight distance sensor 

- README.md
Add DS3231 to the README.md drivers list
> added DS3231 driver to README.md

- .circleci/config.yml
I think this performs the test against all project files using CircleCI.
> ci: perform go fmt test on all files

- .circleci/config.yml
- README.md
- examples/lis3dh/main.go
- lis3dh/lis3dh.go
- lis3dh/registers.go
This PR adds an initial implementation for the lis3dh that can retrieve both raw and scaled accelerometer data.
> lis3dh: initial implementation

- .circleci/config.yml
- README.md
- examples/thermistor/main.go
- thermistor/thermistor.go
This PR add support for thermistors such as the NTC 3950.
> thermistor: add support for thermistors such as the NTC 3950

- .circleci/config.yml
- README.md
- examples/sht3x/main.go
- sht3x/registers.go
- sht3x/sht3x.go
Start of a driver for Sensirion's SHT3x digital temperature and humidity sensor
> SHT3x driver 

- Makefile
- README.md
- examples/waveshare-epd/epd2in13/main.go
- waveshare-epd/epd2in13/epd2in13.go
- waveshare-epd/epd2in13/registers.go
With small modifications (new look up tables) it _might_ be compatible with displays 1.54" (200x200) and 2.9" (296x128), but I have no way to test it.
> support for Waveshare EPD 2.13" display (black&white only)

- microbitmatrix/microbitmatrix.go
This commit ( https://github.com/tinygo-org/tinygo/commit/9f8340a97065c4868dae0d434967183c7a8b1bc6 ) broke the current microbit matrix driver and the CI for the rest
> microbitmatrix: fix for dev branch / volatile package/API

- Makefile
- README.md
- at24cx/at24cx.go
- at24cx/registers.go
- examples/at24cx/main.go
sometimes used in some DS1307/DS3231 modules
> Support for AT24C32/64 2-wire serial EEPROM

- ssd1331/ssd1331.go
> ssd1331: make SPI TX faster

- st7789/st7789.go
This commit adds the same check to the st7789 that also exists in the st7735.
> st7789: fix index out of bounds error

- st7735/registers.go
- st7735/st7735.go
Similar to this PR https://github.com/tinygo-org/drivers/pull/121
> added scroll functionality to st7735

- README.md
º is the masculine ordinal in Spanish. ° is the degree sign. They look different in some fonts.
> README: Use degree sign instead of ordinal

- adt7410/adt7410.go
- bme280/bme280.go
- bmp180/bmp180.go
- drivers.go
- examples/bme280/main.go
- examples/bmp180/main.go
- examples/ds3231/main.go
- examples/mag3110/main.go
- examples/sht3x/main.go
- examples/thermistor/main.go
- lsm6ds3/lsm6ds3.go
- mag3110/mag3110.go
- sht3x/sht3x.go
- thermistor/thermistor.go
Following PR #126 , the degree sign was used in several more places
> Fix degree sign

- ili9341/ili9341.go
- Add SetRotation on Configure func to avoid calling it later
- Fix SetPixel x coord
> some fixes on ili9341 driver

- wifinina/wifinina.go
Didn't test the change myself yet, but looks like a typo
> Wifinina typo

- examples/semihosting/semihosting.go
I could also add a smoke test if needed.
> semihosting: add example

- examples/shifter/main.go
- shifter/shifter.go
this doesn't break existing code, but it might no longer work as expected
> new API for shifter driver.

- ili9341/parallel_atsamd51.go
I've made performance improvements.
1. clear+set in write8() is now set only.
* Instead of being faster, it's more restrictive than ever before.
* In the original, it had to be an 8-bit contiguous port, but this time it has to be an 8-bit contiguous port accessible by StoreUint8().
* If this restriction is unacceptable, it is better not to merge these PRs.
> Improve performance of ILI9341 on ATSAMD5X

- Makefile
- examples/wifinina/ntpclient/main.go
- examples/wifinina/udpstation/main.go
- wifinina/tcp.go
- wifinina/wifinina.go
This PR adds UDP support for the wifinina driver.  Originally I was going to include this in https://github.com/tinygo-org/drivers/pull/156 but because of bug unrelated to UDP, refactoring will require more work.  In the meantime, UDP support can be added via this set of changes.
> wifinina: Support UDP

- examples/st7789/main.go
- st7789/registers.go
- st7789/st7789.go
- corrected bit shift in setWindow that broke high addresses
- added csPin to constructor (will now work with adafruit clue)
- small adjustments and comments to init routine based on working arduino driver
> Fix setWindow bug, add CS pin for Clue compatibility.

- CHANGELOG.md
- go.mod
- version.go
Preparing for Drivers release 0.14.0
> Prepare for Drivers release 0.14.0
