- mag3110/mag3110.go
- mma8653/mma8653.go
- mpu6050/mpu6050.go
Use New() constructor function for devices for simplicity sake. Resolves https://github.com/aykevl/tinygo-drivers/issues/1
> all: use New() constructor function for simplicity

- examples/mpu6050/main.go
This PR adds an example for the MPU6050.
> examples: add example for mpu6050

- ws2812/ws2812_avr_16m.go
- ws2812/ws2812_m0_16m.go
- ws2812/ws2812_m4_64m.go
This commit adds support for the nrf52, which is a Cortex-M4 running at 64MHz.
While implementing this, I discovered that the timings for AVR/16MHz and Cortex-M0 at 16MHz weren't quite right. They do work, but were slightly out of spec. So I fixed this as well.
> ws2812: add nrf52 support, update timings for m0 and avr

- ws2812/ws2812_m0_48m.go
Depends on https://github.com/tinygo-org/tinygo/pull/196 and support for the Playground Express board itself.
> ws2812: add support for Circuit Playground Express

- examples/mag3110/main.go
This PR adds an example for mag3110 magnetometer. Not very much to it.
> examples: add example for mag3110 magnetometer

- examples/mma8653/main.go
- mma8653/mma8653.go
- mma8653/registers.go
This PR improves the mma8653 driver by returning values in a standard unit, and makes this unit configurable (2G, 4G, 8G). I have chose G and not m/s² because that's what is returned by the 2 sensors I looked at (mma8653 and mpu6050).
> mma8653: return acceleration in a standard unit: micro-G.

- examples/blinkm/main.go
This PR adds example code for the BlinkM LED.
> examples: add example code for BlinkM

- bh1750/bh1750.go
- blinkm/blinkm.go
- bmp180/bmp180.go
- mag3110/mag3110.go
- mma8653/mma8653.go
- mpu6050/mpu6050.go
- vl53v1x/vl53l1x.go
This PR refactors all current i2c drivers to use Address property of Driver. It allows variations of a driver to override the default address as discussed in #14
> i2c: refactor all i2c drivers to use Address property of Driver.

- README.md
- bmp180/bmp180.go
- drivers.go
- examples/bmp180/main.go
This PR changes the method names/signature for obtaining temperature/pressure on the BMP180 sensor to be uniform with other similar drivers.
> bmp180: change method names/signature for obtaining temperature/pressure

- display.go
- displayer.go
definition of Display interface
> Define common display interface

- .circleci/config.yml
- README.md
- examples/microbitmatrix/main.go
- microbitmatrix/microbitmatrix.go
There's some code in the board definition that should be removed ( https://github.com/tinygo-org/tinygo/pull/319 )
This driver allows to enable 2 or more leds at a time (vs only 1 led or all leds with the current code at microbit_board.go file)
> Driver for BBC micro:bit on-board LED matrix

- .circleci/config.yml
- README.md
- examples/waveshare-epd/epd2in13x/main.go
- waveshare-epd/epd2in13x/epd2in13x.go
- waveshare-epd/epd2in13x/registers.go
I put it inside the _waveshare-epd_ folder because there're several devices and unfortunately it can not be created a common driver (different registers, power up process, different resolution, colors supported...)
*NOTE:* This driver is for both B (red) and C(yellow) versions, the official implementation/docs refer to the name epd2in13*b*, there's a D version (black/white only) that might be compatible with a few tweaks. A version is a bit more different and I don't think it could be included in the driver. I can't decided which name suits better epd2in13b (as the official name for B & C) or epd2in13x
> Support for Waveshare 2.13" (B & C versions) e-paper display

- easystepper/easystepper.go
- examples/espat/espconsole/main.go
- examples/espat/esphub/main.go
- examples/espat/espstation/main.go
- examples/hd44780/customchar/main.go
- examples/hd44780/text/main.go
- examples/pcd8544/setbuffer/main.go
- examples/pcd8544/setpixel/main.go
- examples/ws2812/main.go
- hd44780/gpio.go
- hd44780/hd44780.go
- hub75/hub75.go
- microbitmatrix/microbitmatrix.go
- pcd8544/pcd8544.go
- ssd1306/ssd1306.go
- thermistor/thermistor.go
- waveshare-epd/epd2in13/epd2in13.go
- waveshare-epd/epd2in13x/epd2in13x.go
- ws2812/ws2812.go
This PR refactors all current drivers to use new machine.Pin interface instead of the older machine.GPIO interface.
In order for it to pass tests and be able to be merged, the PR https://github.com/tinygo-org/tinygo/pull/314 must be merged first.
> all: refactor all current drivers to use new machine.Pin interface

- ws2812/ws2812_m4_64m.go
This has cost me _hours_ to find. There are many clones of the ws2812
and they have slightly different timing characteristics. Some don't work
so well when you get close to the minimum T1H time: a 1-bit may be
interpreted as a 0-bit.
> ws2812: better support the nrf52832

- Makefile
- README.md
- examples/microphone/main.go
- microphone/microphone.go
This PR implements support for PDM MEMS microphones using I2S interface, such as the microphone built-in to the Adafruit Circuit Playground Express.
The PR in the TinyGo repo https://github.com/tinygo-org/tinygo/pull/331 must be merged before this PR can be merged, since it requires the I2S implementation..
> microphone: PDM MEMS microphone support using I2S interface

- ds1307/ds1307.go
- gps/ublox.go
- hd44780/gpio.go
- hd44780/hd44780.go
- pcd8544/pcd8544.go
- ssd1306/ssd1306.go
According to https://github.com/golang/go/wiki/CodeReviewComments#error-strings
> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.
> Error strings should not be capitalized

- mpu6050/mpu6050.go
Units were unspecified before but were in practice the raw output from
the sensor. They have now been changed to sensible outputs
understandable to humans, like the other accelerometers.
> mpu6050: properly scale the outputs of the accel/gyro

- espat/README.md
- espat/commands.go
- espat/espat.go
- espat/mqtt/mqtt.go
- espat/mqtt/paho.go
- espat/net.go
- espat/net/net.go
- espat/tcp.go
- espat/tls/tls.go
- espat/wifi.go
- examples/espat/espconsole/main.go
- examples/espat/esphub/main.go
- examples/espat/espstation/main.go
- examples/espat/mqttclient/main.go
- examples/espat/tcpclient/main.go
This PR adds several important features to the ESP-AT driver:
- ensure compatibility with both ESP8266 and ESP32
- adds support for TLS connections using the ESP-AT command set implementation
- changes the `Reponse()` method to use a timeout value instead of fixed time pauses for better performance and stability
- adds an example program that uses MQTT/MQTTS to publish messages to an MQTT broker.
- adds several more methods that are interface compatible with the `net` package such as `Dial()`.
> espat: update commands

- ws2812/ws2812_m0_48m.go
Uses `atsamd21` to cover anything using the same chip. Should I be more specific?
> ws2812: Add build tag for Arduino Nano33 IoT

- ws2812/ws2812_m0_16m.go
The timings needed to be changed slightly for ws2811 chips which are slightly slower.
Before this change, my string of ws2811 LEDs would flicker slightly (LEDs randomly turning off a very short time). With this extra nop, it's super solid.
> ws2812: fix timings for the nrf51

- Makefile
- README.md
- examples/lsm6ds3/main.go
- lsm6ds3/lsm6ds3.go
- lsm6ds3/registers.go
Initial support for LSM6DS3 IMU (the one in the Arduino Nano33).
It support the pedometer feature, but I didn't fully tested it (my USB cable is not that long), but it works. It also support the temperature readings. Missing FIFO support and SPI, but the one in the nano33 is connected via I2C.
> Initial support for LSM6DS3 IMU

- Makefile
- apa102/apa102.go
- apa102/softspi.go
- examples/apa102/itsybitsy-m0/main.go
Added implementation and example to support software-based SPI for APA102, for use with boards like Adafruit Itsy Bitsy M0 for instance.
Note: I didn't notice any software SPI implementations already in TinyGo so I implemented the minimum necessary to get the APA102 working.  Since it is incomplete for general-purpose use I left that implementation unexported, to make it easier to swap out in case it would make sense to have software SPI be provided by the TinyGo standard library instead at some point in the future.
> Support software SPI for APA102 (Itsy Bitsy M0 on-board "Dotstar" LED as example)

- Makefile
- README.md
- examples/veml6070/main.go
- veml6070/registers.go
- veml6070/veml6070.go
Product: https://www.vishay.com/docs/84277/veml6070.pdf
I would like to contribute support for this UV light sensor to use it easily with tinygo, I tested the submitted code on the sensor I own and it works well. I used this sensor before which is why I created https://github.com/cmur2/python-veml6070
Please give me feedback for this PR, should I change something or is there more documentation to add?
> veml6070: add Vishay UV light sensor

- st7735/st7735.go
Most of the ceremony around pin toggling was in fact unnecessary. This improves performance measurably (roughly 6% in one measurement) and cuts down on binary size by 80 bytes.
> st7735: make SPI Tx faster

- version.go
This PR adds a `Version()` function for support purposes. This was it is easier to report at runtime which version of the drivers package is being used.
> core: add Version() function for support purposes

- Makefile
- README.md
- examples/mcp3008/main.go
- mcp3008/mcp3008.go
This PR adds implementation for MCP3008 ADC with SPI interface.
> mcp3008: add implementation for MCP3008 ADC with SPI interface

- semihosting/semihosting.go
- semihosting/stdio.go
Useful for logging output to the host console.
> semihosting: initial implementation of ARM semihosting

- espat/espat.go
- espat/mqtt/mqtt.go
- espat/mqtt/paho.go
- espat/mqtt/router.go
- espat/mqtt/token.go
- espat/net/net.go
- espat/tcp.go
- espat/wifi.go
- examples/espat/espconsole/main.go
- examples/espat/esphub/main.go
- examples/espat/espstation/main.go
- examples/espat/mqttsub/main.go
- examples/espat/tcpclient/main.go
This PR implements the `Subscribe()` method using channels. It also refactors response processing for greater speed and efficiency.
> espat: implement MQTT subscribe functionality via channels

- ws2812/ws2812_m4_120m.go
- ws2812/ws2812_m4_64m.go
This adjusts the timing for 120MHz as seen on atsamd51 boards. The
timing was kept as close as possible to the Cortex-M4 64MHz logic in
ws2812_m4_64m.go.
Tested: This works on ItsyBitsy-M4
> WS2812: Add support for Cortex-M4 120MHz

- Makefile
This makes it easier to quickly compare all smoke tests for any changes.
> all: add md5sum to smoke tests

- ws2812/ws2812_m0_16m.go
- ws2812/ws2812_m0_48m.go
- ws2812/ws2812_m4_120m.go
- ws2812/ws2812_m4_64m.go
Named local labels shouldn't be used in LLVM because they might get
duplicated resulting in multiple symbol definitions and a compiler
error. Instead, use numeric labels.
---
This fixes just the case for the samd21, other targets also need fixing.
> ws2812: fix "invalid symbol redefinition" error

- ws2812/ws2812_generic.go
- ws2812/ws2812_m0_48m.go
Call a special `__tinygo_ws2812_write_byte` function to send a single byte. It is implemented in the playground with the following PR: https://github.com/tinygo-org/playground/pull/6
> ws2812: add support for simulation

- Makefile
- README.md
- examples/shifter/main.go
- shifter/shifter.go
Simple driver for generic 8/16/32 bit shift registers.
- ReadXXInput, but open to a better name
- One small issue could be the order to read the inputs, not sure if I need to make it configurable
- This will not pass the Ci until pybadge board is added to tinygo
> added generic 8bit shift register

- st7735/st7735.go
- st7789/st7789.go
Remove the default offsets (row/column) it's not possible to set them to 0 (needed for pybadge).
> remove stxx default offsets

- Makefile
- README.md
- adt7410/adt7410.go
- adt7410/registers.go
- examples/adt7410/main.go
This adds basic support (reading a temperature value) for the ADT7410 temperature sensor, which among other things is found on the PyPortal board from Adafruit.
> Support for ADT7410 temperature sensor

- wifinina/Dockerfile
- wifinina/README.md
- wifinina/firmware.sh
This PR provides instructions and a Dockerfile to build the WifiNINA firmware needed to use the Arduino Nano33 IoT and other boards with the Arduino official firmware.
> wifinina: update docs and add Dockerfile to build firmware

- Makefile
- README.md
- examples/l293x/simple/main.go
- examples/l293x/speed/main.go
- l293x/l293x.go
This PR adds support for the L293/L293D/L293N family of H-bridge motor drivers.
> l293x: added support for h-bridge motor driver

- Makefile
- README.md
- examples/l9110x/simple/main.go
- examples/l9110x/speed/main.go
- l9110x/l9110x.go
This PR adds support for the L9110/L9110S motor driver using the same interface as that used by the L293x motor driver.
> l9110x: add support for L9110x h-bridge motor driver

- ws2812/ws2812_m4_64m.go
This adds the nrf52840 tag to the WS2812 driver to support boards like Circuit Playground Bluefruit
> Added nrf52840 tag to ws2812

- Makefile
- README.md
- examples/touch/resistive/fourwire/main.go
- examples/touch/resistive/pyportal_touchpaint/main.go
- touch/point.go
- touch/resistive/fourwire.go
This is a driver for a simple resistive four-wire touchscreen like the one found on PyPortal and many inexpensive displays.
The code works but this PR is still WIP as I am doing some final testing I still need to:
Update README
Add example(s)
Validate the logic
Also I would like to get some feedback on the package layout and interface.  It might be premature for a "standard" interface but I added on called "Pointer" in the touch package.
> Adding driver for four-wire resistive touchscreen

- Makefile
- examples/ws2812/digispark.go
- examples/ws2812/main.go
- examples/ws2812/others.go
- ws2812/ws2812_avr_digispark.go
This PR contains work-arounds to allow Digispark to control WS2812 LEDs. Seems like we discovered some problems in the AVR LLVM backend.
> ws2812: work-arounds to allow Digispark to control WS2812 LEDs

- Makefile
- examples/ili9341/scroll/main.go
- ili9341/ili9341.go
This PR adds a method for setting the vertical scroll address in the ILI9341 driver.
> Adding scroll functionality for ili9341

- net/mqtt/mqtt.go
This PR makes it so the mqtt driver uses buffered channels for incoming messages to handle bursts. 
This appears to improve concurrency for receiving a larger numbers of mqtt subscription events per second then without the buffering.
> mqtt: use buffered channels for incoming messages to handle bursts

- examples/shifter/main.go
- shifter/pybadge.go
- shifter/shifter.go
This PR is intended to simplify API surface and use build directive to directly match the PyBadge.
> shifter: simplify API surface for PyBadge

- README.md
- examples/tmp102/main.go
- tmp102/registers.go
- tmp102/tmp102.go
This adds a driver for the [TMP102](https://download.mikroe.com/documents/datasheets/tmp102-data-sheet.pdf) low-power digital temperature sensor.
Tested on the HiFive1 Rev B with the example code.
> Add driver for TMP102 low-power digital temperature sensor

- net/mqtt/router.go
This PR reduces the use of goroutines in the MQTT router to not start a new goroutine for each invocation of each callback. This helps correct https://github.com/tinygo-org/tinygo/issues/1009 and also seems more realistic in an MCU.
> mqtt: reduce use of goroutines in router

- Makefile
- README.md
- examples/ssd1351/main.go
- ssd1351/commands.go
- ssd1351/ssd1351.go
This implements a driver for the [SSD1351](https://download.mikroe.com/documents/datasheets/ssd1351-revision-1.3.pdf) OLED display controller over SPI.
This driver is based on the code for the SSD1331 controller.
> Add SSD1351 OLED display driver

- ssd1331/ssd1331.go
- ssd1351/ssd1351.go
- st7735/st7735.go
- st7789/st7789.go
DrawFastHLine internally uses FillRectangle(x,y,width,height,c), so height must be 1 to draw a horizontal line
I detected it trying my new 1,44" 128x128 TFT LCD with ST7735 driver, but fixed it in the other drivers, too.
Thank you for your fine work.
> Fix DrawFastHLine for ST77xx, SSD1331 and SSD1351

- apa102/apa102.go
- apa102/softspi.go
Avoid creating unnecessary garbage in the following ways:
* Use the `Transfer` method instead of the `Tx` method for single byte transfers.
* Use a statically allocated buffer for the fixed start-of-frame sequence.
Running this for a few minutes did not cause the garbage collector to run. Previously, it would run every second or so in a persistence-of-vision application, which was clearly visible.
---
Context: I want to build something like [this thing](https://lighttoys.cz/store/vpoi/V4/), which is seriously awesome.
> apa102: avoid creating garbage

- .circleci/config.yml
- go.mod
Since TinyGo started supporting Go modules, there was an error in CI. The commit 7967e82fed423c98e913fc340b5369edc0c4489c tries to fix that, but I think the underlying issue is that we're checking out in `GOROOT`, which is definitely not a supported configuration.
I think the best solution is to just switch to using Go modules, by adding a go.mod file in the root. I've set it to Go version 1.13 as that is the first Go version that supports number literals, but it could be set to any supported Go version (1.11-1.14).
Since we use Go modules, the location of the drivers checkout should not matter so I've removed it. This fixes the error on CircleCI.
> ci: support Go modules

- Makefile
- examples/ili9341/basic/main.go
- examples/ili9341/basic/pyportal.go
- examples/ili9341/basic/wioterminal.go
- examples/ili9341/pyportal_boing/main.go
- examples/ili9341/pyportal_boing/pyportal.go
- examples/ili9341/pyportal_boing/wioterminal.go
- examples/ili9341/scroll/main.go
- examples/ili9341/scroll/pyportal.go
- examples/ili9341/scroll/wioterminal.go
- ili9341/ili9341.go
- ili9341/parallel_atsamd51.go
- ili9341/spi_atsamd51.go
This PR adds SPI support for the ILI9341.
> ILI9341 TFT driver (SPI)

- tmp102/tmp102.go
This PR adds a `Connected()` function for the tmp102 driver. This can be useful to test if the device is properly connected. For example in TinyHCI.
> tmp102: add Connected func to check for device

- bmp180/bmp180.go
I was testing BMP180 again today, and I kept getting weird values.
Turned out the raw temperature data become negative when it convert to int16. I didn't have this problem earlier this year, and I guess it was colder then so the raw data never went higher than 32767. 
Changed a few places to int32 and it works for me. Tested on micro:bit and Nano 33 IoT.
Edit: I have no idea what's going on with CI. Anyone's welcome to fix the BMP180 driver and close this PR.
```
tinygo build -size short -o ./build/test.hex -target=itsybitsy-m0 ./examples/adt7410/main.go
examples/adt7410/main.go:8:2: cannot find package "." in:
/usr/local/go/src/vendor/tinygo.org/x/drivers/adt7410
make: *** [Makefile:12: smoke-test] Error 1
Exited with code exit status 2
```
> Fix BMP180 temperature type conversion

- CONTRIBUTING.md
- apa102/apa102.go
- apa102/softspi.go
- examples/amg88xx/main.go
- examples/flash/console/spi/main.go
- examples/ili9341/basic/wioterminal.go
- examples/ili9341/pyportal_boing/wioterminal.go
- examples/ili9341/scroll/wioterminal.go
- examples/wifinina/mqttclient/main.go
- examples/wifinina/mqttsub/main.go
- examples/wifinina/ntpclient/main.go
- examples/wifinina/tcpclient/main.go
- examples/wifinina/udpstation/main.go
- examples/wifinina/webclient/main.go
- flash/transport_spi.go
- mpu6050/registers.go
- wifinina/wifinina.go
This PR is to changeover to eliminate all direct use of master/slave terminology.
It is intended to match https://github.com/tinygo-org/tinygo/pull/1216 in the main TinyGo repo. Once that PR has been merged, then the tests for this PR will pass again.
See https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names
We will also need to change the master branch name to release, and change the default branch in Github.
> all: changeover to eliminate all direct use of master/slave terminology

- Makefile
- examples/hd44780i2c/main.go
- hd44780i2c/hd44780i2c.go
- hd44780i2c/registers.go
This is for the I2C version of HD44780 LCDs.
The driver is based on some C++/MicroPython drivers and I did try to match the existing HD44780 driver, however the control methods are a bit different (for example, there is no buffer; everything takes effect immediately).
Tested on Arduino Uno/Nano 33 IoT, micro:bit and Adafruit M4 Metro (although the Metro didn't like me to draw 5V power from its pin; only my 3.3V copy worked on it) with both 16x2 and 20x4 versions.
> Add Hd44780i2c driver

- Makefile
- README.md
- bmi160/bmi160.go
- bmi160/registers.go
- examples/bmi160/main.go
Add initial support for the BMI160, which is present on the [GT832C_01](https://www.aliexpress.com/item/4000123520442.html). I haven't actually tested the example because I don't have a separate BMI160, but it does compile. However, this driver works in a project I'm working on.
> bmi160: add initial support

- ili9341/ili9341.go
This is a port of an optimization recently added to the Adafruit_ILI9341 and ILI9341_t3 Arduino drivers.
It works by caching the last row/column sent to the setWindow function, and only resending the respective commands when one of the drawing axes changes. It exhibits a surprisingly effective speedup for basically all drawing operations.
Retrying PR against dev branch instead of master
> ili9341: Cache address window to prevent sending unnecessary commands

- examples/gps/i2c/main.go
- examples/gps/uart/main.go
- gps/gps.go
- gps/gpsparser.go
- gps/registers.go
- gps/ublox.go
This PR add improvements to the GPS driver, by separating the dependencies between the `Driver` and `Parser`. It fixes some issues with performance by removing the reflection. Lastly, it adds support for the RMC NMEA sentence, which is the "other" sentence besides GGA that includes LAt/Long data.
> gps: improvements and bugfixes

- Makefile
- README.md
- examples/lis2mdl/main.go
- lis2mdl/lis2mdl.go
- lis2mdl/registers.go
This PR move the functionality for the LIS2MDL magnetometer into a separate driver for clarity. A future PR will remove the duplication from the current LSM303AGR driver. Thanks @alankrantas for having done most of the work on this already.
> lis2mdl: add LIS2MDL magnetometer

- Makefile
This PR resolves #188 
If I'm going to do it the same way as tinygo-org/tinygo, I think I need to be able to add AVR=0.
I think it is reasonable to add the option because not everyone has avr-gcc installed.
Since the testing of ws2812 is done with circuitplay-express, I think this fix is reasonable.
https://github.com/tinygo-org/tinygo/blob/release/Makefile#L318
before: without avr-gcc installed
```
$ make smoke-test 
...
...
tinygo build -size short -o ./build/test.hex -target=digispark ./examples/ws2812
error: failed to build src/runtime/scheduler_avr.S: exec: "avr-gcc": executable file not found in $PATH
make: *** [Makefile:132: smoke-test] エラー 1
```
after: without avr-gcc installed && with `AVR=0`
```
$ make smoke-test AVR=0
...
...
(ok)
```
> Fix smoke-test unless avr-gcc installed

- Makefile
- README.md
- examples/waveshare-epd/epd4in2/main.go
- waveshare-epd/epd4in2/epd4in2.go
- waveshare-epd/epd4in2/registers.go
Like the other EPD drivers in this repo, this driver is a direct port of the Waveshare reference implementation for Arduino, located at https://github.com/waveshare/e-Paper.
> Add Waveshare 4.2in B/W e-paper driver

- go.mod
- go.sum
- i2c.go
- lis2mdl/lis2mdl.go
- lis2mdl/lis2mdl_test.go
- lis2mdl/registers.go
- tester/device.go
- tester/i2c.go
- tester/tester.go
This PR adds a `tester` package that contains I2CBus and I2CDevice mocks for use in writing unit tests for I2C devices.
Making this PR as draft, it is intended to serve as a starting point for conversation.
> test: add tester package for mocking of I2C bus/devices

- adt7410/adt7410.go
- adxl345/adxl345.go
- amg88xx/amg88xx.go
- at24cx/at24cx.go
- bh1750/bh1750.go
- blinkm/blinkm.go
- bme280/bme280.go
- bmp180/bmp180.go
- bmp280/bmp280.go
- ds1307/ds1307.go
- ds3231/ds3231.go
- gps/gps.go
- hd44780i2c/hd44780i2c.go
- lis3dh/lis3dh.go
- lsm303agr/lsm303agr.go
- lsm6ds3/lsm6ds3.go
- mag3110/mag3110.go
- mma8653/mma8653.go
- mpu6050/mpu6050.go
- sht3x/sht3x.go
- ssd1306/ssd1306.go
- tmp102/tmp102.go
- veml6070/veml6070.go
- vl53l1x/vl53l1x.go
This PR switches all i2c drivers definitions to use i2c bus interface type instead of machine package concrete type.
Once it is merged into `dev`, then individual drivers can have tests added as time permits.
> i2c: switch all i2c drivers definitions to use i2c bus interface type

- examples/st7789/main.go
- st7789/registers.go
- st7789/st7789.go
- FrameRate option sets device framerates from 39-111Hz
- VSyncLines option adjusts device vsync pause using st7789 "porch control" feature
- Added Rx(cmd, bytes[]) to support retrieving scanline timing data over SPI
- Added Sync functions to support synchronization of animation to vertical scanline timing
- Minor adjustments to Configure to clear screen memory before display is visible
> st7789: add support for framerate, vsync pause, and scanline timing

- adt7410/adt7410.go
- adt7410/adt7410_test.go
- adt7410/registers.go
- examples/adt7410/main.go
This PR improves the ADT7410 driver by adding `Connected()`, adding tests, and improving the docs.
> adt7410: add connection test + connection method

- ws2812/ws2812_xtensa.go
This allows WS2812 LEDs to be controlled by an ESP32. Right now it only supports 160MHz operation, which is the default with current ESP32 support in TinyGo.
This PR depends on https://github.com/tinygo-org/tinygo/pull/1354 to work.
> ws2812: add support for the Xtensa architecture

- examples/ili9341/basic/atsamd21.go
- examples/ili9341/basic/wioterminal.go
- examples/ili9341/pyportal_boing/wioterminal.go
- examples/ili9341/scroll/atsamd21.go
- examples/ili9341/scroll/wioterminal.go
- ili9341/spi_atsamd21.go
- ili9341/spi_atsamd51.go
This change renames the NewSpi() constructors for the ILI9341 driver to better follow Go naming conventions, as pointed out in https://github.com/tinygo-org/drivers/pull/196#discussion_r483991299
This is technically a breaking change but I think the disruption should be minimal as the current names have only been a released version of the drivers for about a month.  @sago35 what do you think?
> Renamed NewSpi() to NewSPI() in accordance with Go naming conventions

- ws2812/ws2812_xtensa.go
This patch adds support for the ESP8266 chip by adding support for 80MHz operation. This should also work when the ESP32 is changed to 80MHz, but I didn't test it (as there is not currently a way to do that).
Verified on a NodeMCU dev board with an ESP8266. Depends on https://github.com/tinygo-org/tinygo/pull/900.
> ws2812: add support for ESP8266

- ili9341/ili9341.go
RAMWR can not be skipped as you may call setwindow even if device is not ready for data write to buffer.
Data can only be written if last command was Memory Write or Write Memory Continue which was not guaranteed
There's no performance loss as having the exact same window on a consecutive call is extremely unlikely
Also fixed some typos and added a few missing comments to please go-lint
> ILI9341: Fix for RAMWR bug + cosmetic changes to comments
